// This file centralizes product and category data for easier management and use across the site (e.g., for sitemaps).
// NOTE: This is a sample of products based on previous interactions. You should expand this with all your products.

export const allCategories = [
  {
    id: "shelving",
    title: "სტელაჟები",
    titleEn: "Shelving",
    titleRu: "Стеллажи",
    description: "მაღალი ხარისხის სტელაჟები ნებისმიერი ზომის საწყობისთვის",
    descriptionEn: "High quality shelving for warehouses of any size",
    descriptionRu: "Высококачественные стеллажи для складов любого размера",
    image: "/images/warehouse-shelving.jpg",
    href: "/categories/shelving",
    count: "9 პროდუქტი",
  },
  {
    id: "market-shelves",
    title: "მარკეტის თაროები",
    titleEn: "Market Shelves",
    titleRu: "Торговые полки",
    description: "საგამოფენო თაროები პროდუქტების ეფექტური წარმოსაჩენად",
    descriptionEn: "Display shelves for effective product presentation",
    descriptionRu: "Выставочные полки для эффективной презентации товаров",
    image: "/images/market-shelves.jpg",
    href: "/categories/market-shelves",
    count: "11 პროდუქტი",
  },
  {
    id: "kitchen-shelving",
    title: "სამზარეულოს სტელაჟი",
    titleEn: "Kitchen Shelving",
    titleRu: "Кухонные стеллажи",
    description: "უჟანგავი მეტალის სტელაჟები სამზარეულოსთვის",
    descriptionEn: "Stainless steel shelving for kitchens",
    descriptionRu: "Стеллажи из нержавеющей стали для кухни",
    image: "/images/kitchen-shelving/kitchen-shelf-1.png",
    href: "/categories/kitchen-shelving",
    count: "4 პროდუქტი",
  },
  {
    id: "market-accessories",
    title: "მარკეტის აქსესუარები",
    titleEn: "Market Accessories",
    titleRu: "Аксессуары для магазинов",
    description: "აქსესუარები და დამხმარე მასალები მარკეტებისთვის",
    descriptionEn: "Accessories and auxiliary materials for markets",
    descriptionRu: "Аксессуары и вспомогательные материалы для магазинов",
    image: "/images/market-accessories.jpg",
    href: "/categories/market-accessories",
    count: "5 პროდუქტი",
  },
  {
    id: "pos-materials",
    title: "პოს მასალები",
    titleEn: "POS Materials",
    titleRu: "POS материалы",
    description: "სარეკლამო და საინფორმაციო მასალები მაღაზიებისთვის",
    descriptionEn: "Advertising and information materials for stores",
    descriptionRu: "Рекламные и информационные материалы для магазинов",
    image: "/images/pos-materials.jpg",
    href: "/categories/pos-materials",
    count: "3 პროდუქტი",
  },
  {
    id: "trolleys",
    title: "ურიკები",
    titleEn: "Trolleys",
    titleRu: "Тележки",
    description: "საყიდლების ურიკები და ტრანსპორტირების საშუალებები",
    descriptionEn: "Shopping carts and transportation means",
    descriptionRu: "Тележки для покупок и средства транспортировки",
    image: "/images/trolleys.jpg",
    href: "/categories/trolleys",
    count: "3 პროდუქტი",
  },
  {
    id: "trash-bins",
    title: "ნაგვის ურნები",
    titleEn: "Trash Bins",
    titleRu: "Мусорные баки",
    description: "მაღალი ხარისხის ნაგვის ურნები კომერციული სივრცეებისთვის",
    descriptionEn: "High quality trash bins for commercial spaces",
    descriptionRu: "Высококачественные мусорные баки для коммерческих помещений",
    image: "/images/trash-bins.jpg",
    href: "/categories/trash-bins",
    count: "2 პროდუქტი",
  },
]

export const allProducts = [
  // This is a sample list. You should populate this with all your products.
  { id: "archive-shelving-1", category: "shelving" },
  { id: "market-shelf-single-165", category: "market-shelves" },
  { id: "kitchen-shelf-1", category: "kitchen-shelving" },
  { id: "perforated-panel-hooks", category: "market-accessories" },
  { id: "shelf-price-display-1", category: "pos-materials" },
  { id: "pallet-trolley-red", category: "trolleys" },
  { id: "trash-bin-120l", category: "trash-bins" },
]
